import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const syne = Syne({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
