import Layout from "@/components/layout/Layout";
import { ThemeProvider } from "@/components/theme-provider";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./../globals.css";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const PlusJakartaSans = localFont({
  src: [
    {
      path: "../../../public/font/PlusJakartaSans-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "../../../public/font/PlusJakartaSans-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "AB Learning React",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body className={PlusJakartaSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>
            <Layout>{children}</Layout>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
